# Generated by Django 3.2.7 on 2021-11-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20211126_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
    ]
